// <auto-generated />
using MangaShelf.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MangaShelf.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MangaShelfDbContext))]
    [Migration("20260527144054_AddMangaCred")]
    partial class AddMangaCred
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("MangaShelf.Domain.Entities.Manga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Manga", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "Kentaro Miura",
                            Author = "Kentaro Miura",
                            Description = "A dark fantasy manga following Guts, a lone swordsman marked by tragedy and revenge.",
                            Status = "Reading",
                            Title = "Berserk"
                        },
                        new
                        {
                            Id = 2,
                            Artist = "Takehiko Inoue",
                            Author = "Takehiko Inoue",
                            Description = "A historical samurai manga inspired by the life of Miyamoto Musashi.",
                            Status = "PlanToRead",
                            Title = "Vagabond"
                        },
                        new
                        {
                            Id = 3,
                            Artist = "Makoto Yukimura",
                            Author = "Makoto Yukimura",
                            Description = "A historical manga about war, revenge, slavery, and the search for a peaceful land.",
                            Status = "Completed",
                            Title = "Vinland Saga"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
