// <auto-generated />
using MangaShelf.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MangaShelf.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MangaShelfDbContext))]
    [Migration("20260531005033_AddedChapterPages")]
    partial class AddedChapterPages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("MangaShelf.Domain.Entities.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MangaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MangaId", "Number")
                        .IsUnique();

                    b.ToTable("Chapters", (string)null);
                });

            modelBuilder.Entity("MangaShelf.Domain.Entities.ChapterPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChapterReleaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PageNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChapterReleaseId", "PageNumber")
                        .IsUnique();

                    b.ToTable("ChapterPages", (string)null);
                });

            modelBuilder.Entity("MangaShelf.Domain.Entities.ChapterRelease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScanlatorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScanlatorId");

                    b.HasIndex("ChapterId", "ScanlatorId")
                        .IsUnique();

                    b.ToTable("ChapterReleases", (string)null);
                });

            modelBuilder.Entity("MangaShelf.Domain.Entities.Manga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Manga", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "Kentaro Miura",
                            Author = "Kentaro Miura",
                            Description = "A dark fantasy manga following Guts, a lone swordsman marked by tragedy and revenge.",
                            PublicationStatus = "Hiatus",
                            Title = "Berserk"
                        },
                        new
                        {
                            Id = 2,
                            Artist = "Takehiko Inoue",
                            Author = "Takehiko Inoue",
                            Description = "A historical samurai manga inspired by the life of Miyamoto Musashi.",
                            PublicationStatus = "Discontinued",
                            Title = "Vagabond"
                        },
                        new
                        {
                            Id = 3,
                            Artist = "Makoto Yukimura",
                            Author = "Makoto Yukimura",
                            Description = "A historical manga about war, revenge, slavery, and the search for a peaceful land.",
                            PublicationStatus = "Completed",
                            Title = "Vinland Saga"
                        });
                });

            modelBuilder.Entity("MangaShelf.Domain.Entities.Scanlator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Scanlators", (string)null);
                });

            modelBuilder.Entity("MangaShelf.Domain.Entities.Chapter", b =>
                {
                    b.HasOne("MangaShelf.Domain.Entities.Manga", "Manga")
                        .WithMany()
                        .HasForeignKey("MangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manga");
                });

            modelBuilder.Entity("MangaShelf.Domain.Entities.ChapterPage", b =>
                {
                    b.HasOne("MangaShelf.Domain.Entities.ChapterRelease", "ChapterRelease")
                        .WithMany()
                        .HasForeignKey("ChapterReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChapterRelease");
                });

            modelBuilder.Entity("MangaShelf.Domain.Entities.ChapterRelease", b =>
                {
                    b.HasOne("MangaShelf.Domain.Entities.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaShelf.Domain.Entities.Scanlator", "Scanlator")
                        .WithMany()
                        .HasForeignKey("ScanlatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("Scanlator");
                });
#pragma warning restore 612, 618
        }
    }
}
