// <auto-generated />
using MangaShelf.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MangaShelf.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MangaShelfDbContext))]
    partial class MangaShelfDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("MangaShelf.Domain.Entities.Manga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Manga", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Reading",
                            Title = "Berserk"
                        },
                        new
                        {
                            Id = 2,
                            Status = "PlanToRead",
                            Title = "Vagabond"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Completed",
                            Title = "Vinland Saga"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
